language: ruby
sudo: true
email: false
cache:
  directories:
    - ../bundle
before_install:
  - "pip install boto"
  - "wget -O- -q http://s3tools.org/repo/deb-all/stable/s3tools.key | sudo apt-key add -"
  - "sudo wget -O/etc/apt/sources.list.d/s3tools.list http://s3tools.org/repo/deb-all/stable/s3tools.list"
  - "sudo apt-get update"
  - "sudo apt-get install s3cmd"
bundler_args: "--standalone --without documentation --path ../bundle"
before_script:
  - "bundle exec rake test_server &> /tmp/fakes3_test_server.log&"
  - "TEST_SERVER_PID=$!"
script: "bundle exec rake test"
after_script:
  - "kill -9 $TEST_SERVER_PID"
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - jruby
matrix:
  allow_failures:
    - rvm: 1.9
    - rvm: 2.0
    - rvm: ruby-head
