language: ruby
sudo: true
email: false
cache:
  directories:
    - ../bundle
before_install:
  - "pip install boto"
  - "apt-get install s3cmd"
bundler_args: "--binstubs --standalone --without documentation --path ../bundle"
before_script:
  - "bundle exec rake test_server"
script: "bundle exec rake test"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - jruby
matrix:
  allow_failures:
    - rvm: 1.9
    - rvm: ruby-head
